# Generated by Django 3.0.2 on 2020-03-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybrid',
            name='num_legs',
            field=models.IntegerField(default=4),
        ),
    ]
