# Generated by Django 3.0.2 on 2020-03-17 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_hybrid_num_legs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appt_type', models.CharField(choices=[('H', 'Haircut'), ('D', 'Dentist'), ('L', 'DUI Lawyer'), ('V', 'Vajazzle')], default='Haircut', max_length=1)),
                ('hybrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Hybrid')),
            ],
        ),
    ]
