# Generated by Django 3.0.2 on 2020-03-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appt_type',
            field=models.CharField(choices=[('H', 'Haircut'), ('D', 'Dentist'), ('L', 'DUI Lawyer'), ('V', 'Vajazzle')], default='D', max_length=1),
        ),
    ]
