# Generated by Django 3.0.2 on 2020-03-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200317_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vest_type', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='hybrid',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_type',
            field=models.CharField(choices=[('H', 'Haircut'), ('D', 'Dentist'), ('L', 'DUI Lawyer'), ('V', 'Vajazzle')], default='D', max_length=1, verbose_name='Appointment Type'),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='vests',
            field=models.ManyToManyField(to='main_app.Vest'),
        ),
    ]
